version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/production/lip-api-server

permissions:
  - object: /home/ubuntu/production/lip-api-server
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-production-deploy.sh
      timeout: 300
      runas: ubuntu
